name: Linux Build

on: [ push, pull_request ]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04, windows-2019, windows-2022 ]  # macos-10.15, macos-11,

    steps:
      - uses: actions/checkout@v2

      - name: Install System Dependencies
        shell: bash
        if: runner.os == 'Linux'
        run: sudo apt-get install libffi-dev

      - name: Create Build Directory
        run: cmake -E make_directory ./build/

      - name: Configure CMake
        shell: bash
        working-directory: ./build/
        run: cmake -DCMAKE_BUILD_TYPE=Release -DLINK_WITH_PYTHON=ON ../

      - name: Build MyProgram
        working-directory: ./build/
        shell: bash
        run: cmake --build . --target MyProgram -j 2

      - name: Test MyProgram
        working-directory: ./build/
        shell: bash
        run: |
             if [ "$RUNNER_OS" == "Linux" ]; then
                  ./MyProgram
             elif [ "$RUNNER_OS" == "Windows" ]; then
                  ./Debug/MyProgram.exe
             else
                  ./MyProgram
             fi
        
        
